# Generated by Django 5.0.6 on 2024-10-10 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_gender_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntrp', models.FloatField(blank=True, null=True)),
                ('career_period', models.FloatField(blank=True, null=True)),
                ('active_in_club', models.CharField(blank=True, max_length=100, null=True)),
                ('one_line_introduction', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_amateur', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
