# Generated by Django 5.0.6 on 2024-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='np_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
