# Generated by Django 5.0.6 on 2024-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0003_video_final_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='similarity_cnt',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
