# Generated by Django 5.0.6 on 2024-10-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0004_video_similarity_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='similarity_cnt',
        ),
    ]
